In [51]:
import pandas as pd

EXPLORATION DE LA TABLE CLIENTS

In [52]:
df_clients = pd.read_csv('../data/raw/clients.csv')
df_clients.head()

,client_id,nom,email,ville,date_inscription
0,1,Constance-marguerite jacques,atoussaint@example.org,Fernandesboeuf,2025-08-26
1,2,Michel du andre,vidalleon@example.com,Chauveau,2025-08-04
2,3,Alix da silva,colettelefevre@example.org,Delannoy,2025-08-18
3,4,Laure-laurence brun,vhubert@example.org,Saint Martinnec,2025-06-20
4,5,Théophile lemaître-colin,veroniqueboyer@example.org,Rolland,2025-06-14

In [53]:
df_clients.tail()

,client_id,nom,email,ville,date_inscription
195,196,Nathalie bernard,jacqueline20@example.net,Saint Margaud-sur-Mer,2025-06-08
196,197,Adrien-lucas legrand,aboulay@example.com,Sainte Astrid-les-Bains,2026-03-09
197,198,Éléonore barbe,genevieve21@example.org,Peron,2025-08-05
198,199,Grégoire charpentier,ilagarde@example.com,Perrin-sur-Mer,2025-11-13
199,200,Jérôme louis de la labbé,rouxbernadette@example.com,Allain,2025-05-14

In [54]:
df_clients.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         200 non-null    int64
 1   nom               200 non-null    str
 2   email             192 non-null    str
 3   ville             200 non-null    str
 4   date_inscription  200 non-null    str
dtypes: int64(1), str(4)
memory usage: 7.9 KB

In [55]:
df_clients.describe()

        client_id
count  200.000000
mean   100.500000
std     57.879185
min      1.000000
25%     50.750000
50%    100.500000
75%    150.250000
max    200.000000

In [56]:
df_clients.shape

(200, 5)

EXPLORATION DE LA TABLE COMMANDES

In [57]:
df_commandes = pd.read_csv('../data/raw/commandes.csv')
df_commandes.head()

   commande_id  client_id  produit_id  quantite date_commande  montant_total
0            1         71          16        33    2026-03-20      267738.10
1            2         44          43        78    2025-05-23       -1013.35
2            3        172          25        15    2025-12-20      111486.10
3            4        118          44        64    2026-01-22      663202.55
4            5         67          20        77    2025-05-08      136240.98

In [58]:
df_commandes.tail()

,commande_id,client_id,produit_id,quantite,date_commande,montant_total
1015,520,153,27,74,2025-10-16,891821.17
1016,605,169,12,69,2025-07-01,564560.59
1017,852,159,38,12,2025-07-30,271833.58
1018,263,116,32,19,2025-11-13,957189.91
1019,48,182,46,88,2026-01-25,414615.28

In [59]:
df_commandes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   commande_id    1020 non-null   int64
 1   client_id      1020 non-null   int64
 2   produit_id     1020 non-null   int64
 3   quantite       1020 non-null   int64
 4   date_commande  1020 non-null   str
 5   montant_total  1020 non-null   float64
dtypes: float64(1), int64(4), str(1)
memory usage: 47.9 KB

In [60]:
df_commandes.shape

(1020, 6)

In [61]:
df_commandes.describe()

       commande_id    client_id   produit_id     quantite  montant_total
count  1020.000000  1020.000000  1020.000000  1020.000000    1020.000000
mean    500.954902   102.900000    26.274510    54.502941  489289.479637
std     288.862644    58.159773    14.597348    26.471808  305441.241768
min       1.000000     1.000000     1.000000    10.000000   -1814.810000
25%     251.750000    55.000000    14.000000    32.000000  212071.427500
50%     501.500000   103.000000    27.000000    54.000000  500961.665000
75%     751.250000   154.000000    39.000000    78.000000  756376.307500
max    1000.000000   200.000000    50.000000   100.000000  997922.840000

EXPLORATION DE LA TABLE PRODUITS

In [62]:
df_produits = pd.read_csv('../data/raw/produits.csv')
df_produits.head()

   produit_id        nom categorie     prix
0           1    éclat16     Photo   899.52
1           2  séparer17        Tv   905.50
2           3   figurer8     Audio   851.20
3           4   pointe16     Photo  1053.02
4           5  camarade9     Photo   168.79

In [63]:
df_produits.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   produit_id  50 non-null     int64
 1   nom         50 non-null     str
 2   categorie   50 non-null     str
 3   prix        50 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 1.7 KB

In [64]:
df_produits.describe()

       produit_id         prix
count    50.00000    50.000000
mean     25.50000  1042.110200
std      14.57738   540.654898
min       1.00000   168.790000
25%      13.25000   620.957500
50%      25.50000  1052.090000
75%      37.75000  1411.200000
max      50.00000  1963.380000

In [65]:
df_produits.shape

(50, 4)

In [66]:
import sqlite3

In [68]:
conn = sqlite3.connect("../src/data/02_RetailPulse.db")

In [81]:
df_CA_mensuel=pd.read_sql("select round(sum(montant_total),2) as Chiffre_affaire , strftime('%Y-%m', date_commande) as Mois from commandes GROUP BY strftime('%Y-%m', date_commande) ORDER BY strftime('%Y-%m', date_commande) ASC;",conn)
df_CA_mensuel

    Chiffre_affaire     Mois
0       38535985.24  2025-04
1       41222032.62  2025-05
2       43957520.67  2025-06
3       40114191.75  2025-07
4       46792793.17  2025-08
5       35614622.86  2025-09
6       39591160.01  2025-10
7       45317864.10  2025-11
8       37567423.77  2025-12
9       42869865.12  2026-01
10      33596773.80  2026-02
11      48149756.56  2026-03
12       5248217.31  2026-04

In [80]:
df_top_produits=pd.read_sql("select produits.produit_id,produits.nom,produits.categorie,round(sum(commandes.montant_total),2) as revenue from produits left join commandes on produits.produit_id = commandes.produit_id group by produits.produit_id ORDER BY revenue DESC LIMIT 5;",conn)
df_top_produits

   produit_id         nom     categorie      revenue
0          46  réveiller6         Photo  15728466.14
1          50  paupière16         Audio  15147544.97
2          45    phrase15    Telephonie  14492147.68
3          16     auteur7         Photo  14294467.13
4          42   prochain9  Informatique  13691166.70

In [79]:
clients_vip=("""select clients.client_id,
       clients.nom,
       clients.ville,
       round(COALESCE(sum(commandes.montant_total),0),2) as depenses 
from clients
left join commandes
on clients.client_id = commandes.client_id
group by clients.client_id
ORDER BY depenses DESC
LIMIT 10;""")
df_clients_vip=pd.read_sql_query(clients_vip,conn)
df_clients_vip

   client_id                        nom                    ville    depenses
0        172              Grégoire noël                    Henry  6062321.03
1        148               Lucie delmas                   Pierre  6024135.06
2         41          Sabine le olivier                   Turpin  5822438.95
3        102  Louise chevallier-roussel                    Neveu  5413185.62
4        169           Honoré petitjean               Lambertnec  5237365.05
5        124         Patrick le delorme          Maillot-sur-Mer  5230368.26
6         15    Pauline gilbert-bruneau             Saint Sylvie  5070041.32
7          2       Louise le carpentier                   Boutin  4758206.07
8        126           Jérôme martineau          Sainte Dorothée  4684960.18
9         21            Bertrand devaux  Saint Dominique-sur-Mer  4484907.69

In [82]:
periodes_creuses=("""select COUNT(*) as nbre_commandes,strftime('%Y-%m', date_commande) as mois 
from commandes
GROUP BY mois 
ORDER BY nbre_commandes ASC
LIMIT 3;
""")
df_periodes_creuses=pd.read_sql_query(periodes_creuses,conn)
df_periodes_creuses

   nbre_commandes     mois
0               8  2026-04
1              72  2025-04
2              74  2025-12